### ISSUE TITLE
Concerns

### ISSUE THREAD

**Issue by rdirocco** [kevinquinnyo/hamster-sweaters#6]
With no updates in the last 26 days I'm concerned about the viability of production deployment without continued support.

Is this project abandoned?

**Comment by kevinquinnyo** [comment]
rdirocco,

Thank you for your interest in Hamster Sweaters.  We value your input.  You seem to be having an issue with  "Concerns" .   An internal ticket has been opened in our system for your issue and a representative will be with you shortly.  Your ticket number is #99348783947289 .  

Thank you!
Hamster Sweaters, Inc

**Comment by kevinquinnyo** [comment]
Hi <Customer Name Here> !

I'm a customer-experience engineer here at Hamster Sweaters, Inc .  I understand you are still having some issues with <Issue Title> .  I just want to let you know that we haven't forgotten about your issue with <Issue Title> and our team of IT/Development Ninjas are working hard to resolve this issue.

Your ticket number is #99348783947289 . 

Thank you!
Hamster Sweaters, Inc
